version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    env_file: .env
    depends_on:
      - postgres
    networks:
      - app-network
    healthcheck:
      test: curl --fail http://localhost:3333/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file: .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
